vich_uploader:
    db_driver: orm


    mappings:
        photo_image:
            uri_prefix: '%kernel.project_dir%/public/uploads'
            upload_destination: '%kernel.project_dir%/public/uploads'